---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  become: false

  tasks:
    - name: Pull image from Docker Hub
      community.docker.docker_image:
        name: subhamagarwal05/scientific-calculator # Use your DockerHub username
        source: pull

    - name: Stop and remove existing container if it exists
      community.docker.docker_container:
        name: calculator_app
        state: absent

    - name: Run calculator container
      community.docker.docker_container:
        name: calculator_app
        image: subhamagarwal05/scientific-calculator # Use your DockerHub username
        state: started
        ports:
          - "8081:8080" # Map container port 8080 to host port 8081
        restart_policy: always